/* 
 * Copyright (C) 2013 Harokopio University <Nikolaos Zormpas>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gr.hua.gui.Preprocessor;

import gr.hua.data_manipulation.Change;
import gr.hua.gui.MainMenu;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;

/**
 *
 * @author r0t0r
 */
public class FNRDialog extends javax.swing.JDialog {

    private DefaultListModel valuesModel = new DefaultListModel();
    private DefaultListModel replacementsModel = new DefaultListModel();
    private String[] curvalues;
    int indx1 = 0;
    int indx2 = 0;
    private LinkedList<Change> changes = new LinkedList();
    /**
     * Creates new form FNRDialog
     */
    public FNRDialog(java.awt.Frame parent, boolean modal, String[] values) {
        super(parent, modal);
        initComponents();
        curvalues = values;
        valuesL.setSelectionMode(
                DefaultListSelectionModel.SINGLE_SELECTION);
        replacementsL.setSelectionMode(
                DefaultListSelectionModel.SINGLE_SELECTION);
        valuesL.setModel(valuesModel);
        replacementsL.setModel(replacementsModel);
        load();
    }
    
    private void load() {
        valuesModel.removeAllElements();
        replacementsModel.removeAllElements();
        for (String s : curvalues) {
            if (s == null) {
                continue;
            }
            valuesModel.addElement(s);
            replacementsModel.addElement(s);
        }
        if (!replacementsModel.isEmpty()) {
            if (indx2 > replacementsModel.getSize()) {
                replacementsL.setSelectedIndex(replacementsModel.getSize() - 1);
            } else if (indx2 != -1) {
                replacementsL.setSelectedIndex(indx2);
            } else {
                replacementsL.setSelectedIndex(0);
            }
        }
        if (!valuesModel.isEmpty()) {
            if (indx1 > valuesModel.getSize()) {
                valuesL.setSelectedIndex(valuesModel.getSize() - 1);
            } else if (indx1 != -1) {
                valuesL.setSelectedIndex(indx1);
            } else {
                valuesL.setSelectedIndex(0);
            }
        }
    }
    
    public LinkedList<Change> open() {
        setVisible(true);
        return changes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        valuesL = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        newValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        replacementsL = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        valuesL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        valuesL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valuesLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(valuesL);

        jLabel1.setText("Available Values");

        jLabel3.setText("Replace With:");

        jButton1.setText("Replace");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Replacements");

        replacementsL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        replacementsL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                replacementsLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(replacementsL);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Accept");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3)))))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(MainMenu.main, "Are you sure you"
                + "want to replace '" + valuesModel.getElementAt(indx1) + "' "
                + "with '" + newValue.getText() + "' ?") 
                == JOptionPane.YES_OPTION) {
            Change temp = new Change(valuesModel.getElementAt(indx1).toString(), newValue.getText());
            changes.add(temp);
            curvalues[indx1] = null;
            int dist = 0;
            for (int i = 0; i < curvalues.length; i++) {
                if (curvalues[i] == null) {
                    dist++;
                } else {
                    curvalues[i - dist] = curvalues[i];
                    curvalues[i] = null;
                }
            }
            load();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void replacementsLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replacementsLMouseClicked
        indx2 = replacementsL.getSelectedIndex();
        indx1 = valuesL.getSelectedIndex();
        newValue.setText(replacementsModel.getElementAt(indx2).toString());
    }//GEN-LAST:event_replacementsLMouseClicked

    private void valuesLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valuesLMouseClicked
        indx2 = replacementsL.getSelectedIndex();
        indx1 = valuesL.getSelectedIndex();
        newValue.setText(valuesModel.getElementAt(indx1).toString());
    }//GEN-LAST:event_valuesLMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        changes = null;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField newValue;
    private javax.swing.JList replacementsL;
    private javax.swing.JList valuesL;
    // End of variables declaration//GEN-END:variables
}
