/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gr.hua.gui.DataMiner;

import gr.hua.data_structures.DataColumn;
import gr.hua.gui.MainMenu;
import gr.hua.gui.Tab;
import gr.hua.weka_bridge.CloneableAttribute;
import gr.hua.weka_bridge.Trainer;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author r0t0r
 */
public class DataMinerTab extends Tab {

    private int id1 = 0, id2 = 0, id3 = 0;
    private ArrayList<JListItem> columns;
    private ArrayList<MiningMethodPanel> alMiningMethods = new ArrayList();

    public DataMinerTab(MainMenu parent, String title) {
        super(parent, title);
        initComponents();
        columnsList.setModel(new MyDefaultListModel());
        selColumnsList.setModel(new MyDefaultListModel());
        targetList.setModel(new MyDefaultListModel());
        targetList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        loadMiner();
        miningMethods.setLayout(new BoxLayout(miningMethods, BoxLayout.Y_AXIS));
        for (int i : MiningMethodPanel.methods) {
            miningMethods.add(MiningMethodPanel.getInstance(i));
            alMiningMethods.add(MiningMethodPanel.getInstance(i));
        }
        topResultsSP.setEnabled(false);
        topResultsSP.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        resultsL.setEnabled(false);
        miningMethods.revalidate();
    }

    private boolean checkForDuplicates() {
        for (int i = 0; i < columns.size() - 1; i++) {
            for (int j = i + 1; j < columns.size(); j++) {
                if (columns.get(i).getLabel().equals(columns.get(j).getLabel())) {
                    return false;
                }
            }
        }
        if (!autoAttributesCB.isSelected()) {
            if (((MyDefaultListModel) selColumnsList.getModel()).contains(targetList.getSelectedValue())) {
                return false;
            }
        }
        return true;
    }

    private void initColumns() {
        columns = new ArrayList();
        for (int i = 0; i < MainMenu.MANAGER.getNumberOfColumns(); i++) {
            DataColumn temp = MainMenu.MANAGER.getColumn(i);
            columns.add(new JListItem(temp.getName(), i, temp.getAttribute(), columnsList));
        }
    }

    private void loadMiner() {
        if (!MainMenu.MANAGER.ready()) {
            return;
        }
        ((MyDefaultListModel) columnsList.getModel()).removeAllElements();
        ((MyDefaultListModel) targetList.getModel()).removeAllElements();
        ((MyDefaultListModel) selColumnsList.getModel()).removeAllElements();
        for (JListItem item : columns) {
            ((MyDefaultListModel) item.getParent().getModel()).addElement(item);
        }
        for (JListItem j : ((MyDefaultListModel) columnsList.getModel()).toArray()) {
            ((MyDefaultListModel) targetList.getModel()).addElement(j);
        }
        columnsList.setSelectedIndex(id1);
        selColumnsList.setSelectedIndex(id2);
        targetList.setSelectedIndex(id3);
    }

    private void savePositions() {
        id1 = columnsList.getSelectedIndex();
        id2 = selColumnsList.getSelectedIndex();
        id3 = targetList.getSelectedIndex();
    }

    private void collectProperties(Properties p) {
        if (autoAttributesCB.isSelected() || autoSelAttributesCB.isSelected()) {
            p.setProperty(Trainer.OPTIMIZE_ATTRIBUTES, "ON");
            p.setProperty(Trainer.SET_TOP_RESULTS, topResultsSP.getValue().toString());
        }
    }
    
    private CloneableAttribute targetAttribute() {
        JListItem item = (JListItem) targetList.getSelectedValue();
        String name = ((CloneableAttribute) item.getValue()).name();
        String[] names = MainMenu.MANAGER.getColumnNames();
        for (int i = 0; i < names.length; i++) {
            if (names[i].equals(name)) {
                return MainMenu.MANAGER.getColumn(i).getForcedNominalAttribute();
            }
        }
        return null;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valuesScr = new javax.swing.JScrollPane();
        columnsList = new javax.swing.JList();
        addB = new javax.swing.JButton();
        valuesScr1 = new javax.swing.JScrollPane();
        selColumnsList = new javax.swing.JList();
        removeB = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        valuesScr2 = new javax.swing.JScrollPane();
        targetList = new javax.swing.JList();
        jLabel38 = new javax.swing.JLabel();
        mineB = new javax.swing.JButton();
        autoAttributesCB = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        container = new javax.swing.JScrollPane();
        miningMethods = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        autoSelAttributesCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        resultsL = new javax.swing.JLabel();
        topResultsSP = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(800, 640));
        setMinimumSize(new java.awt.Dimension(800, 640));
        setPreferredSize(new java.awt.Dimension(800, 640));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        valuesScr.setMaximumSize(new java.awt.Dimension(149, 130));
        valuesScr.setMinimumSize(new java.awt.Dimension(149, 130));

        columnsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        columnsList.setMaximumSize(null);
        columnsList.setMinimumSize(null);
        columnsList.setPreferredSize(null);
        valuesScr.setViewportView(columnsList);

        addB.setText("Add");
        addB.setMaximumSize(new java.awt.Dimension(71, 23));
        addB.setMinimumSize(new java.awt.Dimension(90, 23));
        addB.setPreferredSize(new java.awt.Dimension(90, 23));
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        valuesScr1.setMaximumSize(new java.awt.Dimension(149, 130));
        valuesScr1.setMinimumSize(new java.awt.Dimension(149, 130));

        selColumnsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        selColumnsList.setMaximumSize(null);
        selColumnsList.setMinimumSize(null);
        selColumnsList.setPreferredSize(null);
        valuesScr1.setViewportView(selColumnsList);

        removeB.setText("Remove");
        removeB.setMaximumSize(new java.awt.Dimension(90, 23));
        removeB.setMinimumSize(new java.awt.Dimension(90, 23));
        removeB.setPreferredSize(new java.awt.Dimension(90, 23));
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        jLabel37.setText("Select target column:");

        valuesScr2.setMaximumSize(new java.awt.Dimension(149, 130));
        valuesScr2.setMinimumSize(new java.awt.Dimension(149, 130));

        targetList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        targetList.setMaximumSize(null);
        targetList.setMinimumSize(null);
        targetList.setPreferredSize(null);
        valuesScr2.setViewportView(targetList);

        jLabel38.setText("Data Mining methods:");

        mineB.setText("Mine");
        mineB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineBActionPerformed(evt);
            }
        });

        autoAttributesCB.setText("Choose Attributes automatically from all attributes");
        autoAttributesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoAttributesCBActionPerformed(evt);
            }
        });

        jLabel39.setText("Select attributes:");

        jLabel1.setText("Selected attributes:");

        javax.swing.GroupLayout miningMethodsLayout = new javax.swing.GroupLayout(miningMethods);
        miningMethods.setLayout(miningMethodsLayout);
        miningMethodsLayout.setHorizontalGroup(
            miningMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        miningMethodsLayout.setVerticalGroup(
            miningMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        container.setViewportView(miningMethods);

        jLabel2.setText("Select optimizations:");

        autoSelAttributesCB.setText("Choose automatically only");
        autoSelAttributesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSelAttributesCBActionPerformed(evt);
            }
        });

        jLabel3.setText("from those selected above");

        resultsL.setText("Top results to save:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(valuesScr, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(autoAttributesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(valuesScr1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(autoSelAttributesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(resultsL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(topResultsSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mineB)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valuesScr2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel1)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addComponent(valuesScr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valuesScr2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(valuesScr1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoAttributesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoSelAttributesCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(resultsL)
                        .addComponent(topResultsSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mineB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        savePositions();
        int[] id = columnsList.getSelectedIndices();
        if (id1 != -1) {
            for (int i = 0; i < id.length; i++) {
                ((MyDefaultListModel) columnsList.getModel()).get(id[i]).setParent(selColumnsList);
            }
            loadMiner();
        }
    }//GEN-LAST:event_addBActionPerformed

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        savePositions();
        int[] id = selColumnsList.getSelectedIndices();
        if (id2 != -1) {
            for (int i = 0; i < id.length; i++) {
                ((MyDefaultListModel) selColumnsList.getModel()).get(id[i]).setParent(columnsList);
            }
            loadMiner();
        }
    }//GEN-LAST:event_removeBActionPerformed

    private void mineBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineBActionPerformed
        if (!MainMenu.MANAGER.ready()) {
            JOptionPane.showMessageDialog(this, "There are errors in the currently open file! Please fix them before mining.");
            return;
        } else if (!checkForDuplicates()) {
            JOptionPane.showMessageDialog(this, "Duplicate column names are not allowed!");
            return;
        }
        ResultsArea resArea = new ResultsArea(MainMenu.main, true);
        Properties prop = new Properties();
        collectProperties(prop);
        CloneableAttribute target = targetAttribute();
        if (target == null) {
            JOptionPane.showMessageDialog(this,
                    "Couldn't turn target column into a nominal attribute!");
            return;
        }
        ArrayList<CloneableAttribute> selColumns = new ArrayList();
        for (JListItem j : columns) {
            if (!autoAttributesCB.isSelected() && j.getParent() == selColumnsList) {
                selColumns.add((CloneableAttribute) j.getValue());
            } else if (autoAttributesCB.isSelected()) {
                String name = ((CloneableAttribute) j.getValue()).name();
                if (!name.equals(target.name())) {
                    selColumns.add((CloneableAttribute) j.getValue());
                }
            }
        }
        for (MiningMethodPanel m : alMiningMethods) {
            if (m.checked()) {
                m.mine(resArea, selColumns, target, prop);
            }
        }
        resArea.open();
        for (MiningMethodPanel m : alMiningMethods) {
            if (m.checked()) {
                m.stop();
            }
        }
    }//GEN-LAST:event_mineBActionPerformed

    private void autoAttributesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoAttributesCBActionPerformed
        columnsList.setEnabled(!autoAttributesCB.isSelected());
        selColumnsList.setEnabled(!autoAttributesCB.isSelected());
        autoSelAttributesCB.setEnabled(!autoAttributesCB.isSelected());
        topResultsSP.setEnabled(autoSelAttributesCB.isSelected() || autoAttributesCB.isSelected());
        resultsL.setEnabled(autoSelAttributesCB.isSelected() || autoAttributesCB.isSelected());
    }//GEN-LAST:event_autoAttributesCBActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        initColumns();
        loadMiner();
    }//GEN-LAST:event_formComponentShown

    private void autoSelAttributesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoSelAttributesCBActionPerformed
        autoAttributesCB.setEnabled(!autoSelAttributesCB.isSelected());
        topResultsSP.setEnabled(autoSelAttributesCB.isSelected() || autoAttributesCB.isSelected());
        resultsL.setEnabled(autoSelAttributesCB.isSelected() || autoAttributesCB.isSelected());
    }//GEN-LAST:event_autoSelAttributesCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JCheckBox autoAttributesCB;
    private javax.swing.JCheckBox autoSelAttributesCB;
    private javax.swing.JList columnsList;
    private javax.swing.JScrollPane container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mineB;
    private javax.swing.JPanel miningMethods;
    private javax.swing.JButton removeB;
    private javax.swing.JLabel resultsL;
    private javax.swing.JList selColumnsList;
    private javax.swing.JList targetList;
    private javax.swing.JSpinner topResultsSP;
    private javax.swing.JScrollPane valuesScr;
    private javax.swing.JScrollPane valuesScr1;
    private javax.swing.JScrollPane valuesScr2;
    // End of variables declaration//GEN-END:variables
}
